version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 48770660
      MYSQL_DATABASE: administracionproyectos
    ports:
      - "3307:3306"

volumes:
  db_data: